import { PRODUCT_TYPES } from './templatesConfig.js';

export const designs = [
  // --- Prayer Card Designs ---
  {
    id: 'prayercard_design1',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_1_Dove_Right_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_2_Dove_Right_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_1_Dove_Right_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_2_Dove_Right_Back_Bleed.jpg',
    label: 'Dove Right',
    nameFont: { family: 'MonteCarloRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', weight: 'normal', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
    front: {
      overlays: [
        {
          src: './templates/prayer_cards/overlays/Prayer_Cards_01_ Overlay_Dove.png',
          x: 0,
          y: 0,
          width: 750,
          height: 1200,
        },
      ],
    },
  },
  {
    id: 'prayercard_design2',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_4',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_3_Dove_Left_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_4_Dove_Left_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_3_Dove_Left_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_4_Dove_Left_Back_Bleed.jpg',
    label: 'Dove Left',
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design3',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_4',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_5_Cardinal_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_6_Cardinal_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_5_Cardinal_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_6_Cardinal_Back_Bleed.jpg',
    label: 'Cardinal',
    borderColor: '#000',
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design4',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_4',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_7_American_Flag_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_8_American_Flag_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_7_American_Flag_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_8_American_Flag_Back_Bleed.jpg',
    label: 'American Flag',
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#000' },
  },
  {
    id: 'prayercard_design5',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_9_American_Flag_with_Blue_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_10_American_Flag_with_Blue_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_9_American_Flag_Blue_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_10_American_Flag_Blue_Back_Bleed.jpg',
    label: 'American Flag with Blue',
    borderColor: 'white',
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#fff' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#fff' },
  },
  {
    id: 'prayercard_design6',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_11_Gray_Black_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_12_Gray_Black_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_11_Gray_Black_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_12_Gray_Black_Back_Bleed.jpg',
    label: 'Gray Black',
    borderColor: '#000',
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design7',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_13_Blue_Velvet_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_14_Blue_Velvet_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_13_Blue_Velvet_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_14_Blue_Velvet_Back_Bleed.jpg',
    label: 'Blue Velvet',
    borderColor: '#000',
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#000' },
  },
  {
    id: 'prayercard_design8',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_15_Teal_Floral_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_16_Teal_Floral_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_15_Teal_Floral_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_16_Teal_Floral_Back_Bleed.jpg',
    label: 'Teal Floral',
    nameFont: { family: 'PinyonScriptRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design9',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_17_Beach_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_18_Beach_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_17_Beach_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_18_Beach_Back_Bleed.jpg',
    label: 'Beach',
    nameFont: { family: 'Birthstone', size: '29px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '29px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '29px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '29px', color: '#000' },
  },
  {
    id: 'prayercard_design10',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_19_Pink_Floral_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_20_Pink_Floral_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_19_Pink_Floral_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_20_Pink_Floral_Back_Bleed.jpg',
    label: 'Pink Floral',
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design11',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_21_Eucalyptus_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_22_Eucalyptus_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_21_Eucalyptus_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_22_Eucalyptus_Back_Bleed.jpg',
    label: 'Eucalyptus',
    nameFont: { family: 'ImperialScriptRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design12',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_23_Baby_w_Pic_Blue_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_24_Baby_w_Pic_Blue_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_23_Baby_w_Pic_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_24_Baby_w_Pic_Back_Bleed.jpg',
    label: 'Baby with Pic Blue',
    nameFont: { family: 'MonteCarloRegular', size: '20px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '20px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#000' },
  },
  {
    id: 'prayercard_design13',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_2',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_25_Angel_Baby_Pink_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_26_Angel_Baby_Pink_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_25_Angel_Baby_Pink_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_26_Angel_Baby_Pink_Back_Bleed.jpg',
    label: 'Angel Baby Pink',
    nameFont: { family: 'MonteCarloRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design14',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_2',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_27_Angel_Baby_Blue_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_28_Angel_Baby_Blue_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_27_Angel_Baby_Blue_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_28_Angel_Baby_Blue_Back_Bleed.jpg',
    label: 'Angel Baby Blue',
    nameFont: { family: 'MonteCarloRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design15',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_29_Baby_Toys_w_Pic_Tan_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_30_Baby_Toys_w_Pic_Tan_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_29_Baby_Toys_w_Pic_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_30_Baby_Toys_w_Pic_Back_Bleed.jpg',
    label: 'Baby Toys with Pic Tan',
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design16',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_2',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_31_Rainbow_Baby_1_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_32_Rainbow_Baby_1_Pink_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_31_Rainbow_Baby_Pink_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_32_Rainbow_Baby_Pink_Back_Bleed.jpg',
    label: 'Rainbow Baby 1',
    nameFont: { family: 'Birthstone', size: '24px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '24px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '24px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '24px', color: '#000' },
  },
  {
    id: 'prayercard_design17',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_2',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_33_Rainbow_Baby_2_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_34_Rainbow_Baby_2_Blue_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_33_Rainbow_Baby_Blue_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_34_Rainbow_Baby_Blue_Back_Bleed.jpg',
    label: 'Rainbow Baby 2',
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design18',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_2',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_35_Rainbow_Baby_3_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_36_Rainbow_Baby_3_Green_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_35_Rainbow_Baby_Green_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_36_Rainbow_Baby_Green_Back_Bleed.jpg',
    label: 'Rainbow Baby 3',
    nameFont: { family: 'Birthstone', size: '23px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '23px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '23px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '23px', color: '#000' },
  },
  {
    id: 'prayercard_design19',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_37_Teddy_Bear_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_38_Teddy_Bear_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_37_Teddy_Bear_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_38_Teddy_Bear_Back_Bleed.jpg',
    label: 'Teddy Bear',
    nameFont: { family: 'DancingScriptRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
    front: {
      overlays: [
        {
          src: './templates/prayer_cards/overlays/Prayer_Cards_37_Overlay_Teddy_Bear.png',
          x: 0,
          y: 0,
          width: 750,
          height: 1200,
        },
      ],
    },
  },
  {
    id: 'prayercard_design20',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_2',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_39_Androgenous_Baby_on_Snow_Cloud_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_40_Androgenous_Baby_on_Snow_Cloud_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_39_Androgenous_Baby_on_Snow_Cloud_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_40_Androgenous_Baby_on_Snow_Cloud_Back_Bleed.jpg',
    label: 'Androgenous Baby on Snow Cloud',
    nameFont: { family: 'PoppinsRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'prayercard_design21',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_41_Tricycle_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_42_Tricycle_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_41_Tricycle_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_42_Tricycle_Back_Bleed.jpg',
    label: 'Tricycle',
    borderColor: '#000',
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#080164' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#080164' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#080164' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#080164' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#080164' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#080164' },
    front: {
      overlays: [
        {
          src: './templates/prayer_cards/overlays/Prayer_Cards_41_Overlay_Tricycle.png',
          x: 0,
          y: 0,
          width: 750,
          height: 1200,
        },
      ],
    },
  },
  {
    id: 'prayercard_design22',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_4',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_43_Pink_Rose_Tan_Marble_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_44_Pink_Rose_Tan_Marble_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_43_Pink_Rose_Tan_Marble_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_44_Pink_Rose_Tan_Marble_Back_Bleed.jpg',
    label: 'Pink Rose Tan Marble',
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
    front: {
      overlays: [
        {
          src: './templates/prayer_cards/overlays/Prayer_Cards_43_Overlay_Pink_Rose.png',
          x: 0,
          y: 0,
          width: 750,
          height: 1200,
        },
      ],
    },
  },
  {
    id: 'prayercard_design23',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_1',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_45_Yellow_Pink_Rose_on_Tan_Marble_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_46_Yellow_Pink_Rose_on_Tan_Marble_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_45_Yellow_Pink_Rose_on_Tan_Marble_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_46_Yellow_Pink_Rose_on_Tan_Marble_Back_Bleed.jpg',
    label: 'Yellow Pink Rose on Tan Marble',
    borderColor: 'gold',
    nameFont: { family: 'Birthstone', size: '23px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '23px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '23px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '23px', color: '#000' },
  },
  {
    id: 'prayercard_design24',
    productType: PRODUCT_TYPES.PRAYER_CARD,
    templateId: 'pc_template_5',
    frontImage: './templates/prayer_cards/jpeg/Prayer_Cards_47_Prayer_for_Unborn_Child_Front.jpg',
    backImage: './templates/prayer_cards/jpeg/Prayer_Cards_48_Prayer_for_Unborn_Child_Back.jpg',
    frontImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_47_Prayer_for_Unborn_Child_Front_Bleed.jpg',
    backImageBleed: './templates/prayer_cards/bleed/Prayer_Cards_48_Prayer_for_Unborn_Child_Back_Bleed.jpg',
    label: 'Prayer for Unborn Child',
    nameFont: { family: 'Arial', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'Arial', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  // --- Bookmark Designs ---
  {
    id: 'bookmark_design1',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_3',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_1_Dove_Right_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_2_Dove_Right_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_1_Dove_Right_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_2_Dove_Right_Back_Bleed.jpg",
    label: "Dove Right",
    // borderColor: '#000',
    nameFont: { family: 'MonteCarloRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design2',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_3_Dove_Left_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_4_Dove_Left_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_3_Dove_Left_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_4_Dove_Left_Back_Bleed.jpg",
    label: "Dove Left",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design3',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_5_Cardinal_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_6_Cardinal_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_5_Cardinal_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_6_Cardinal_Back_Bleed.jpg",
    label: "Cardinal",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design4',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_7_American_Flag_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_8_American_Flag_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_7_American_Flag_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_8_American_Flag_Back_Bleed.jpg",
    label: "American Flag",
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#000' },
  },
  {
    id: 'bookmark_design5',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_9_American_Flag_with_Blue_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_10_American_Flag_with_Blue_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_9_American_Flag_Blue_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_10_American_Flag_Blue_Back_Bleed.jpg",
    label: "American Flag with Blue",
    borderColor: '#fff',
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#fff' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#fff' },
  },
  {
    id: 'bookmark_design6',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_6',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_11_Gray_Black_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_12_Gray_Black_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_11_Gray_Black_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_12_Gray_Black_Back_Bleed.jpg",
    label: "Gray Black",
    borderColor: '#000',
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design7',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_13_Blue_Velvet_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_14_Blue_Velvet_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_13_Blue_Velvet_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_14_Blue_Velvet_Back_Bleed.jpg",
    label: "Blue Velvet",
    borderColor: '#000',
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#000' },
  },
  {
    id: 'bookmark_design8',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_3',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_15_Teal_Floral_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_16_Teal_Floral_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_15_Teal_Floral_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_16_Teal_Floral_Back_Bleed.jpg",
    label: "Teal Floral",
    nameFont: { family: 'PinyonScriptRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design9',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_3',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_17_Beach_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_18_Beach_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_17_Beach_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_18_Beach_Back_Bleed.jpg",
    label: "Beach",
    nameFont: { family: 'Birthstone', size: '29px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '29px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#000' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#000' },
    prayerFont: { family: 'CrimsonTextRegular', size: '29px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '29px', color: '#000' },
  },
  {
    id: 'bookmark_design10',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_19_Pink_Floral_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_20_Pink_Floral_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_19_Pink_Floral_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_20_Pink_Floral_Back_Bleed.jpg",
    label: "Pink Floral",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design11',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_3',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_21_Eucalyptus_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_22_Eucalyptus_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_21_Eucalyptus_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_22_Eucalyptus_Back_Bleed.jpg",
    label: "Eucalyptus",
    nameFont: { family: 'ImperialScriptRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design12',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_23_Baby_w_Pic_Blue_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_24_Baby_w_Pic_Blue_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_23_Baby_w_Pic_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_24_Baby_w_Pic_Back_Bleed.jpg",
    label: "Baby with Pic Blue",
    nameFont: { family: 'MonteCarloRegular', size: '20px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '20px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#000' },
  },
  {
    id: 'bookmark_design13',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_2',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_25_Angel_Baby_Pink_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_26_Angel_Baby_Pink_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_25_Angel_Baby_Pink_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_26_Angel_Baby_Pink_Back_Bleed.jpg",
    label: "Angel Baby Pink",
    nameFont: { family: 'MonteCarloRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design14',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_2',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_27_Angel_Baby_Blue_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_28_Angel_Baby_Blue_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_27_Angel_Baby_Blue_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_28_Angel_Baby_Blue_Back_Bleed.jpg",
    label: "Angel Baby Blue",
    nameFont: { family: 'MonteCarloRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design15',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_29_Baby_Toys_w_Pic_Tan_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_30_Baby_Toys_w_Pic_Tan_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_29_Baby_Toys_w_Pic_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_30_Baby_Toys_w_Pic_Back_Bleed.jpg",
    label: "Baby Toys with Pic Tan",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design16',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_5',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_31_Rainbow_Baby_1_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_32_Rainbow_Baby_1_Pink_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_31_Rainbow_Baby_Pink_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_32_Rainbow_Baby_Pink_Back_Bleed.jpg",
    label: "Rainbow Baby 1",
    nameFont: { family: 'Birthstone', size: '24px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '24px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '24px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '24px', color: '#000' },
  },
  {
    id: 'bookmark_design17',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_5',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_33_Rainbow_Baby_2_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_34_Rainbow_Baby_2_Blue_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_33_Rainbow_Baby_Blue_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_34_Rainbow_Baby_Blue_Back_Bleed.jpg",
    label: "Rainbow Baby 2",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design18',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_5',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_35_Rainbow_Baby_3_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_36_Rainbow_Baby_3_Green_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_35_Rainbow_Baby_Green_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_36_Rainbow_Baby_Green_Back_Bleed.jpg",
    label: "Rainbow Baby 3",
    nameFont: { family: 'Birthstone', size: '23px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '23px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '23px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '23px', color: '#000' },
  },
  {
    id: 'bookmark_design19',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_37_Teddy_Bear_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_38_Teddy_Bear_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_37_Teddy_Bear_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_38_Teddy_Bear_Back_Bleed.jpg",
    label: "Teddy Bear",
    borderColor: 'gold',
    nameFont: { family: 'DancingScriptRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design20',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_5',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_39_Androgenous_Baby_on_Snow_Cloud_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_40_Androgenous_Baby_on_Snow_Cloud_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_39_Androgenous_Baby_on_Snow_Cloud_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_40_Androgenous_Baby_on_Snow_Cloud_Back_Bleed.jpg",
    label: "Androgenous Baby on Snow Cloud",
    nameFont: { family: 'PoppinsRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design21',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_41_Tricycle_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_42_Tricycle_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_41_Tricycle_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_42_Tricycle_Back_Bleed.jpg",
    label: "Tricycle",
    borderColor: '#000',
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '20px', color: '#000' },
  },
  {
    id: 'bookmark_design22',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_1',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_43_Pink_Rose_Tan_Marble_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_44_Pink_Rose_Tan_Marble_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_43_Pink_Rose_Tan_Marble_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_44_Pink_Rose_Tan_Marble_Back_Bleed.jpg",
    label: "Pink Rose Tan Marble",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  {
    id: 'bookmark_design23',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_3',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_45_Yellow_Pink_Rose_on_Tan_Marble_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_46_Yellow_Pink_Rose_on_Tan_Marble_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_45_Yellow_Pink_Rose_on_Tan_Marble_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_46_Yellow_Pink_Rose_on_Tan_Marble_Back_Bleed.jpg",
    label: "Yellow Pink Rose on Tan Marble",
    borderColor: 'gold',
    nameFont: { family: 'Birthstone', size: '23px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '23px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '23px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '23px', color: '#000' },
  },
  {
    id: 'bookmark_design24',
    productType: PRODUCT_TYPES.BOOKMARK,
    templateId: 'bm_template_4',
    frontImage: "./templates/bookmarks/jpeg/Bookmarks_47_Prayer_for_Unborn_Child_Front.jpg",
    backImage: "./templates/bookmarks/jpeg/Bookmarks_48_Prayer_for_Unborn_Child_Back.jpg",
    frontImageBleed: "./templates/bookmarks/bleed/Bookmark_47_Prayer_for_Unborn_Child_Front_Bleed.jpg",
    backImageBleed: "./templates/bookmarks/bleed/Bookmark_48_Prayer_for_Unborn_Child_Back_Bleed.jpg",
    label: "Prayer for Unborn Child",
    nameFont: { family: 'Arial', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'Arial', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'PoppinsRegular', size: '22px', color: '#000' },
  },
  // --- Memorial Hearts Designs ---
  {
    id: 'memorialheart_design1',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_2',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_1_Dove_Right_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_2_Dove_Right_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_1_Dove_Right_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_2_Dove_Right_Back_Bleed.jpg",
    label: "Dove Right",
    nameFont: { family: 'MonteCarloRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design2',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_3_Dove_Left_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_4_Dove_Left_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_3_Dove_Left_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_4_Dove_Left_Back_Bleed.jpg",
    label: "Dove Left",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design3',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_5_Cardinal_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_6_Cardinal_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_5_Cardinal_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_6_Cardinal_Back_Bleed.jpg",
    label: "Cardinal",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design4',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_7_American_Flag_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_8_American_Flag_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_7_American_Flag_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_8_American_Flag_Back_Bleed.jpg",
    label: "American Flag",
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '20px', color: '#000' },
  },
  {
    id: 'memorialheart_design5',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_9_American_Flag_Blue_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_10_American_Flag_Blue_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_9_American_Flag_Blue_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_10_American_Flag_Blue_Back_Bleed.jpg",
    label: "American Flag Blue",
    borderColor: '#fff',
    nameFont: { family: 'CrimsonTextSemiBold', size: '20px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '20px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#fff' },
    prayerFontAlt: { family: 'Arial', size: '20px', color: '#fff' },
  },
  {
    id: 'memorialheart_design6',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_2',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_11_Gray_Black_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_12_Gray_Black_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_11_Gray_Black_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_12_Gray_Black_Back_Bleed.jpg",
    label: "Gray Black",
    borderColor: '#000',
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#fff' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#fff' },
  },
  {
    id: 'memorialheart_design7',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_2',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_13_Blue_Velvet_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_14_Blue_Velvet_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_13_Blue_Velvet_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_14_Blue_Velvet_Back_Bleed.jpg",
    label: "Blue Velvet",
    borderColor: 'black',
    nameFont: { family: 'CrimsonTextSemiBold', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design8',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_2',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_15_Teal_Floral_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_16_Teal_Floral_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_15_Teal_Floral_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_16_Teal_Floral_Back_Bleed.jpg",
    label: "Teal Floral",
    nameFont: { family: 'PinyonScriptRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design9',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_2',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_17_Beach_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_18_Beach_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_17_Beach_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_18_Beach_Back_Bleed.jpg",
    label: "Beach",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design10',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_19_Pink_Floral_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_20_Pink_Floral_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_19_Pink_Floral_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_20_Pink_Floral_Back_Bleed.jpg",
    label: "Pink Floral",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design11',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_2',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_21_Eucalyptus_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_22_Eucalyptus_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_21_Eucalyptus_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_22_Eucalyptus_Back_Bleed.jpg",
    label: "Eucalyptus",
    nameFont: { family: 'ImperialScriptRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design12',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_23_Baby_w_Pic_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_24_Baby_w_Pic_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_23_Baby_w_Pic_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_24_Baby_w_Pic_Back_Bleed.jpg",
    label: "Baby w Pic",
    nameFont: { family: 'MonteCarloRegular', size: '20px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '20px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '20px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '20px', color: '#000' },
  },
  {
    id: 'memorialheart_design13',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_3',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_25_Angel_Baby_Pink_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_26_Angel_Baby_Pink_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_25_Angel_Baby_Pink_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_26_Angel_Baby_Pink_Back_Bleed.jpg",
    label: "Angel Baby Pink",
    nameFont: { family: 'MonteCarloRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design14',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_3',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_27_Angel_Baby_Blue_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_28_Angel_Baby_Blue_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_27_Angel_Baby_Blue_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_28_Angel_Baby_Blue_Back_Bleed.jpg",
    label: "Angel Baby Blue",
    nameFont: { family: 'MonteCarloRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design15',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_29_Baby_Toys_w_Pic_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_30_Baby_Toys_w_Pic_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_29_Baby_Toys_w_Pic_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_30_Baby_Toys_w_Pic_Back_Bleed.jpg",
    label: "Baby Toys w Pic",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design16',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_3',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_31_Rainbow_Baby_Pink_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_32_Rainbow_Baby_Pink_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_31_Rainbow_Baby_Pink_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_32_Rainbow_Baby_Pink_Back_Bleed.jpg",
    label: "Rainbow Baby Pink",
    nameFont: { family: 'Birthstone', size: '24px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '24px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '24px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '24px', color: '#000' },
  },
  {
    id: 'memorialheart_design17',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_3',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_33_Rainbow_Baby_Blue_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_34_Rainbow_Baby_Blue_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_33_Rainbow_Baby_Blue_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_34_Rainbow_Baby_Blue_Back_Bleed.jpg",
    label: "Rainbow Baby Blue",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design18',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_3',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_35_Rainbow_Baby_Green_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_36_Rainbow_Baby_Green_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_35_Rainbow_Baby_Green_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_36_Rainbow_Baby_Green_Back_Bleed.jpg",
    label: "Rainbow Baby Green",
    nameFont: { family: 'Birthstone', size: '23px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '23px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '23px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '23px', color: '#000' },
  },
  {
    id: 'memorialheart_design19',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_37_Teddy_Bear_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_38_Teddy_Bear_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_37_Teddy_Bear_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_38_Teddy_Bear_Back_Bleed.jpg",
    label: "Teddy Bear",
    nameFont: { family: 'DancingScriptRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design20',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_3',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_39_Androgenous_Baby_on_Snow_Cloud_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_40_Androgenous_Baby_on_Snow_Cloud_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_39_Androgenous_Baby_on_Snow_Cloud_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_40_Androgenous_Baby_on_Snow_Cloud_Back_Bleed.jpg",
    label: "Androgenous Baby on Snow Cloud",
    nameFont: { family: 'PoppinsRegular', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design21',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_41_Tricycle_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_42_Tricycle_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_41_Tricycle_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_42_Tricycle_Back_Bleed.jpg",
    label: "Tricycle",
    borderColor: '#000',
    nameFont: { family: 'CrimsonTextSemiBold', size: '22px', weight: 'normal', color: '#080164' },
    nameFontAlt: { family: 'MonteCarloRegular', size: '22px', color: '#080164' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#080164' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#080164' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#080164' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#080164' },
  },
  {
    id: 'memorialheart_design22',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_1',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_43_Pink_Rose_Tan_Marble_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_44_Pink_Rose_Tan_Marble_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_43_Pink_Rose_Tan_Marble_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_44_Pink_Rose_Tan_Marble_Back_Bleed.jpg",
    label: "Pink Rose Tan Marble",
    nameFont: { family: 'Birthstone', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  },
  {
    id: 'memorialheart_design23',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_2',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_45_Yellow_Pink_Rose_on_Tan_Marble_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_46_Yellow_Pink_Rose_on_Tan_Marble_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_45_Yellow_Pink_Rose_on_Tan_Marble_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_46_Yellow_Pink_Rose_on_Tan_Marble_Back_Bleed.jpg",
    label: "Yellow Pink Rose on Tan Marble",
    borderColor: 'gold',
    nameFont: { family: 'Birthstone', size: '23px', weight: 'normal', color: '#fff' },
    nameFontAlt: { family: 'CrimsonTextSemiBold', size: '23px', color: '#fff' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#fff' },
    prayerFont: { family: 'CrimsonTextRegular', size: '23px', weight: 'normal', color: '#fff' },
    prayerFontAlt: { family: 'Arial', size: '23px', color: '#fff' },
  },
  {
    id: 'memorialheart_design24',
    productType: PRODUCT_TYPES.MEMORIAL_HEART,
    templateId: 'mh_template_4',
    frontImage: "./templates/memorial_hearts/jpeg/Heart-Cards_47_Prayer_for_Unborn_Child_Front.jpg",
    backImage: "./templates/memorial_hearts/jpeg/Heart-Cards_48_Prayer_for_Unborn_Child_Back.jpg",
    frontImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_47_Prayer_for_Unborn_Child_Front_Bleed.jpg",
    backImageBleed: "./templates/memorial_hearts/bleed/Heart-Cards_48_Prayer_for_Unborn_Child_Back_Bleed.jpg",
    label: "Prayer for Unborn Child",
    nameFont: { family: 'Arial', size: '22px', weight: 'normal', color: '#000' },
    nameFontAlt: { family: 'Arial', size: '22px', color: '#000' },
    dateFont: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    dateFontAlt: { family: 'PoppinsRegular', size: '7px', weight: 'normal', color: '#444' },
    prayerFont: { family: 'CrimsonTextRegular', size: '22px', weight: 'normal', color: '#000' },
    prayerFontAlt: { family: 'Arial', size: '22px', color: '#000' },
  }
];