

export const PRODUCT_TYPES = {
  PRAYER_CARD: 'prayer_card',
  BOOKMARK: 'bookmark',
};

export const templatesConfig = {
  [PRODUCT_TYPES.PRAYER_CARD]: {
    label: 'Prayer Card',
    widthPx: 750,
    heightPx: 1200,
    bleedWidthPx: 780,   // Adjust later @Elias
    bleedHeightPx: 1230, // Adjust later @Elias
    templates: [
      {
        id: 'pc_template_1',
        label: 'Template 1 - Full Info',
        front: {
          elements: {
            photo: {
              x: 88,
              y: 133,
              width: 575,
              height: 635,
              borderRadius: '50%',
              hasPhoto: true,
            },
            name: {
              x: 215,
              y: 880,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '64px', weight: 'normal', color: '#000' },
              hasText: true,
            },
            // middleName: {
            //   x: 200,
            //   y: 450,
            //   width: 350,
            //   height: 40,
            //   font: { family: 'Arial', size: '20px', weight: 'normal', color: '#222' },
            //   hasText: true,
            // },
            lastName: {
              x: 390,
              y: 880,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '64px', weight: 'normal', color: '#000' },
              hasText: true,
            },
            dob: {
              x: 100,
              y: 990,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#444' },
              hasText: true,
            },
            dod: {
              x: 362,
              y: 990,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#444' },
              hasText: true,
            },
          },
        },
        back: {
          elements: {
            note: {
              x: 100,
              y: 100,
              width: 550,
              height: 400,
              font: { family: 'Arial', size: '16px', color: '#000' },
              hasText: true,
            },
            proverb: {
              x: 180,
              y: 190,
              width: 400,
              height: 60,
              font: { family: 'Times New Roman', size: '16px', weight: 'normal', color: '#555', italic: true },
              hasText: true,
            },
          },
        },
      },
      {
        id: 'pc_template_1_fontWhite',
        label: 'Template 1 - Full Info',
        front: {
          elements: {
            photo: {
              x: 95,
              y: 143,
              width: 560,
              height: 620,
              borderRadius: '50%',
              hasPhoto: true,
            },
            name: {
              x: 215,
              y: 890,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '64px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            // middleName: {
            //   x: 200,
            //   y: 450,
            //   width: 350,
            //   height: 40,
            //   font: { family: 'Arial', size: '20px', weight: 'normal', color: '#222' },
            //   hasText: true,
            // },
            lastName: {
              x: 390,
              y: 890,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '64px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            dob: {
              x: 100,
              y: 990,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            dod: {
              x: 362,
              y: 990,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
          },
        },
        back: {
          elements: {
            note: {
              x: 100,
              y: 100,
              width: 550,
              height: 400,
              font: { family: 'Arial', size: '16px', color: '#000' },
              hasText: true,
            },
            proverb: {
              x: 180,
              y: 190,
              width: 400,
              height: 60,
              font: { family: 'Times New Roman', size: '16px', weight: 'normal', color: '#fff', italic: true },
              hasText: true,
            },
          },
        },
      },
      {
        id: 'pc_template_1_fontWhite_backFontBlack',
        label: 'Template 1 - Full Info',
        front: {
          elements: {
            photo: {
              x: 95,
              y: 143,
              width: 560,
              height: 620,
              borderRadius: '50%',
              hasPhoto: true,
            },
            name: {
              x: 215,
              y: 890,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '64px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            // middleName: {
            //   x: 200,
            //   y: 450,
            //   width: 350,
            //   height: 40,
            //   font: { family: 'Arial', size: '20px', weight: 'normal', color: '#222' },
            //   hasText: true,
            // },
            lastName: {
              x: 390,
              y: 890,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '64px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            dob: {
              x: 100,
              y: 990,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            dod: {
              x: 362,
              y: 990,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
          },
        },
        back: {
          elements: {
            note: {
              x: 100,
              y: 100,
              width: 550,
              height: 400,
              font: { family: 'Arial', size: '16px', color: '#000' },
              hasText: true,
            },
            proverb: {
              x: 180,
              y: 190,
              width: 400,
              height: 60,
              font: { family: 'Times New Roman', size: '16px', weight: 'normal', color: '#000', italic: true },
              hasText: true,
            },
          },
        },
      },
      {
        id: 'pc_template_2',
        label: 'Template 2 - Full Info',
        front: {
          elements: {
            photo: {
              x: 94,
              y: 231,
              width: 560,
              height: 620,
              borderRadius: '50%',
              hasPhoto: true,
            },
            name: {
              x: 215,
              y: 960,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '54px', weight: 'normal', color: '#000' },
              hasText: true,
            },
            // middleName: {
            //   x: 200,
            //   y: 450,
            //   width: 350,
            //   height: 40,
            //   font: { family: 'Arial', size: '20px', weight: 'normal', color: '#222' },
            //   hasText: true,
            // },
            lastName: {
              x: 380,
              y: 960,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '54px', weight: 'normal', color: '#000' },
              hasText: true,
            },
            dob: {
              x: 100,
              y: 1050,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#444' },
              hasText: true,
            },
            dod: {
              x: 362,
              y: 1050,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#444' },
              hasText: true,
            },
          },
        },
        back: {
          elements: {
            note: {
              x: 100,
              y: 100,
              width: 550,
              height: 400,
              font: { family: 'Arial', size: '16px', color: '#000' },
              hasText: true,
            },
            proverb: {
              x: 180,
              y: 190,
              width: 400,
              height: 60,
              font: { family: 'Times New Roman', size: '16px', weight: 'normal', color: '#555', italic: true },
              hasText: true,
            },
          },
        },
      },
      {
        id: 'pc_template_2_fontWhite',
        label: 'Template 2 - Full Info',
        front: {
          elements: {
            photo: {
              x: 94,
              y: 231,
              width: 560,
              height: 620,
              borderRadius: '50%',
              hasPhoto: true,
            },
            name: {
              x: 215,
              y: 960,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '54px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            // middleName: {
            //   x: 200,
            //   y: 450,
            //   width: 350,
            //   height: 40,
            //   font: { family: 'Arial', size: '20px', weight: 'normal', color: '#222' },
            //   hasText: true,
            // },
            lastName: {
              x: 380,
              y: 960,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '54px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            dob: {
              x: 100,
              y: 1050,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            dod: {
              x: 362,
              y: 1050,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
          },
        },
        back: {
          elements: {
            note: {
              x: 100,
              y: 100,
              width: 550,
              height: 400,
              font: { family: 'Arial', size: '16px', color: '#000' },
              hasText: true,
            },
            proverb: {
              x: 180,
              y: 190,
              width: 400,
              height: 60,
              font: { family: 'Times New Roman', size: '16px', weight: 'normal', color: '#fff', italic: true },
              hasText: true,
            },
          },
        },
      },
      {
        id: 'pc_template_2_fontWhite_backFontBlack',
        label: 'Template 2 - Full Info',
        front: {
          elements: {
            photo: {
              x: 94,
              y: 231,
              width: 560,
              height: 620,
              borderRadius: '50%',
              hasPhoto: true,
            },
            name: {
              x: 215,
              y: 960,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '54px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            // middleName: {
            //   x: 200,
            //   y: 450,
            //   width: 350,
            //   height: 40,
            //   font: { family: 'Arial', size: '20px', weight: 'normal', color: '#222' },
            //   hasText: true,
            // },
            lastName: {
              x: 380,
              y: 960,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '54px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            dob: {
              x: 100,
              y: 1050,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
            dod: {
              x: 362,
              y: 1050,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#fff' },
              hasText: true,
            },
          },
        },
        back: {
          elements: {
            note: {
              x: 100,
              y: 100,
              width: 550,
              height: 400,
              font: { family: 'Arial', size: '16px', color: '#000' },
              hasText: true,
            },
            proverb: {
              x: 180,
              y: 190,
              width: 400,
              height: 60,
              font: { family: 'Times New Roman', size: '16px', weight: 'normal', color: '#000', italic: true },
              hasText: true,
            },
          },
        },
      },
      {
        id: 'pc_template_3',
        label: 'Template 3 - Full Info',
        front: {
          elements: {
            // photo: {
            //   x: 95,
            //   y: 143,
            //   width: 560,
            //   height: 620,
            //   borderRadius: '50%',
            //   hasPhoto: true,
            // },
            name: {
              x: 215,
              y: 850,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '74px', weight: 'normal', color: '#000' },
              hasText: true,
            },
            // middleName: {
            //   x: 200,
            //   y: 450,
            //   width: 350,
            //   height: 40,
            //   font: { family: 'Arial', size: '20px', weight: 'normal', color: '#222' },
            //   hasText: true,
            // },
            lastName: {
              x: 390,
              y: 850,
              width: 170,
              height: 40,
              font: { family: 'Arial', size: '74px', weight: 'normal', color: '#000' },
              hasText: true,
            },
            dob: {
              x: 100,
              y: 955,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#444' },
              hasText: true,
            },
            dod: {
              x: 362,
              y: 955,
              width: 310,
              height: 30,
              font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#444' },
              hasText: true,
            },
          },
        },
        back: {
          elements: {
            note: {
              x: 100,
              y: 100,
              width: 550,
              height: 400,
              font: { family: 'Arial', size: '16px', color: '#000' },
              hasText: true,
            },
            proverb: {
              x: 180,
              y: 190,
              width: 400,
              height: 60,
              font: { family: 'Times New Roman', size: '16px', weight: 'normal', color: '#555', italic: true },
              hasText: true,
            },
          },
        },
      },
      {
        id: 'pc_template_4',
        label: 'Template 4 - Full Info',
        front: {
          elements: {
            // photo: {
            //   x: 95,
            //   y: 143,
            //   width: 560,
            //   height: 620,
            //   borderRadius: '50%',
            //   hasPhoto: true,
            // },
            // name: {
            //   x: 215,
            //   y: 865,
            //   width: 170,
            //   height: 40,
            //   font: { family: 'Arial', size: '54px', weight: 'normal', color: '#000' },
            //   hasText: true,
            // },
            // middleName: {
            //   x: 200,
            //   y: 450,
            //   width: 350,
            //   height: 40,
            //   font: { family: 'Arial', size: '20px', weight: 'normal', color: '#222' },
            //   hasText: true,
            // },
            // lastName: {
            //   x: 390,
            //   y: 865,
            //   width: 170,
            //   height: 40,
            //   font: { family: 'Arial', size: '54px', weight: 'normal', color: '#000' },
            //   hasText: true,
            // },
            // dob: {
            //   x: 100,
            //   y: 955,
            //   width: 310,
            //   height: 30,
            //   font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#444' },
            //   hasText: true,
            // },
            // dod: {
            //   x: 362,
            //   y: 955,
            //   width: 310,
            //   height: 30,
            //   font: { family: 'Georgia', size: '34px', weight: 'normal', color: '#444' },
            //   hasText: true,
            // },
          },
        },
        back: {
          elements: {
            note: {
              x: 100,
              y: 100,
              width: 550,
              height: 400,
              font: { family: 'Arial', size: '16px', color: '#000' },
              hasText: true,
            },
            proverb: {
              x: 180,
              y: 190,
              width: 400,
              height: 60,
              font: { family: 'Times New Roman', size: '16px', weight: 'normal', color: '#555', italic: true },
              hasText: true,
            },
          },
        },
      },
    ],
  },

  [PRODUCT_TYPES.BOOKMARK]: {
    label: 'Bookmark',
    widthPx: 675,
    heightPx: 2100,
    bleedWidthPx: 705,
    bleedHeightPx: 2130,
    templates: [
      {
        id: 'bm_template_1',
        label: 'Template 1 - Name, Dates, Photo',
        front: {
          elements: {
            photo: {
              x: 86,
              y: 200,
              width: 504,
              height: 504,
              borderRadius: '50%',
              hasPhoto: true,
            },
            name: {
              x: 80,
              y: 790,
              width: 260,
              height: 60,
              font: { family: 'Arial', size: '44px', weight: 'bold', color: '#222', italic: true },
              hasText: true,
            },
            lastName: {
              x: 280,
              y: 790,
              width: 260,
              height: 60,
              font: { family: 'Arial', size: '44px', weight: 'bold', color: '#222', italic: true },
              hasText: true,
            },
            dob: {
              x: 125,
              y: 710,
              width: 400,
              height: 30,
              font: { family: 'Georgia', size: '18px', weight: 'normal', color: '#555', },
              hasText: true,
            },
            dod: {
              x: 125,
              y: 750,
              width: 400,
              height: 30,
              font: { family: 'Georgia', size: '18px', weight: 'normal', color: '#555' },
              hasText: true,
            },
          },
        },
        back: {
          elements: {
            proverb: {
              x: 100,
              y: 300,
              width: 480,
              height: 80,
              font: { family: 'Times New Roman', size: '28px', color: '#333', italic: true },
              hasText: true,
            },
          },
        },
      },
      {
        id: 'bm_template_2',
        label: 'Template 2 - Text Only',
        front: {
          elements: {
            name: {
              x: 100,
              y: 300,
              width: 480,
              height: 40,
              font: { family: 'Helvetica', size: '20px', color: '#111' },
              hasText: true,
            },
            proverb: {
              x: 100,
              y: 400,
              width: 480,
              height: 100,
              font: { family: 'Helvetica', size: '18px', color: '#444', italic: false },
              hasText: true,
            },
          },
        },
        back: {
          elements: {
            note: {
              x: 90,
              y: 250,
              width: 500,
              height: 200,
              font: { family: 'Arial', size: '16px', color: '#000' },
              hasText: true,
            },
          },
        },
      },
    ],
  },
};